### ISSUE TITLE
[FEATURE] Ability to delete all checklists within a System

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openrmf-web#109]
**Is your feature request related to a problem? Please describe.**
I would like to be able to delete all checklists within a system, to re-upload my checklists.

**Describe the solution you'd like**
I would like to be able to delete all checklists within a system, to re-upload my checklists.

**Describe alternatives you've considered**
delete all checklists on at a time.  PIA.

**Additional context**

**Comment by Cingulara** [comment]
![image](https://user-images.githubusercontent.com/46137145/71044927-1a691680-2101-11ea-9e38-ed8d0f7e95f8.png)

**Comment by Cingulara** [comment]
![image](https://user-images.githubusercontent.com/46137145/71322628-b98e6500-2497-11ea-8d5f-c0314ae328d3.png)
