### ISSUE TITLE
[FEATURE] Delete entire system

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openrmf-web#110]
**Describe the solution you'd like**
The ability to delete an entire system....checklists and all.  To recreate the system from scratch or to remove all together.

**Comment by Cingulara** [comment]
Allow deleting an entire system if an Editor or Admin.  With a button like below. Calls DELETE /systemId or something. 
* delete all checklists
* delete the system
* delete all scores
* add audit history for "delete" saved
* log on each delete action
* "Delete" = deleted boolean record
* deletedDate is a nullable date for when the record was deleted
* eventual consistency = NATS clients do the deleting

![image](https://user-images.githubusercontent.com/46137145/71044997-58fed100-2101-11ea-9f99-ae3b0749dbf3.png)

**Comment by Cingulara** [comment]
Getting the delete working now with logging. Will have to add in Auditing under the auditing ticket.

**Comment by Cingulara** [comment]
If you have editor or admin permissions:
![image](https://user-images.githubusercontent.com/46137145/71307722-9644b680-23c0-11ea-926e-a4901d9cd67f.png)

**Comment by Cingulara** [comment]
Confirmation on all deletes.
![image](https://user-images.githubusercontent.com/46137145/71307753-e58ae700-23c0-11ea-9530-13d3dae05c7b.png)

**Comment by Cingulara** [comment]
Working well. Removing every system now to see what you get at first start.
