### ISSUE TITLE
[BUG] "Add new system" with checklist does not show on second load.

### ISSUE THREAD

**Issue by mtnnomad6970** [Cingulara/openrmf-web#122]
Uploading multiple checklists into a new system works the first time, but the drop-down list on the system list will not show the correct systems on the second checklist upload.  Clicking to another page and returning fixes the problem.

**To Reproduce**
1. Go to Upload page
2. Click on 'add new system' and type in the name.
3. choose a checklist for this system and upload and save.
4. Add in another checklist by looking for that System, the pull-down list contains a list that is not complete.

To refresh, click on another page (i.e. Report) and return to "Upload" and the drop-down list is corrected.

**Expected behavior**
After uploading into a new system, the page should refresh the list prior to future uploads.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 79.0.2945.88

**Comment by Cingulara** [comment]
I saw this the other day yes. I will check out tonight/tomorrow morning.

**Comment by Cingulara** [comment]
Fixed and ready for Demo online
