### ISSUE TITLE
[FEATURE] Can we upload checklists into a general bin and then assign them to Systems at a later date?

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-web#123]
I am uploading a set of checklists from a large production system with a large number of servers.  The checklists are from IE, OS, DC, Domain, etc.  We track the "System" as a whole, but it would be nice to create or link checklists to systems so we can isolate issues per STIG. 

If I load 100 - 200 checklists into the tool, and I want to focus specifically on Windows 2008 Member Servers, OS only, I'd like to be able to associate the checklists with that "system" so I can identify issues with that STIG alone.  

Currently I have loaded all 2008 MS OS STIG Checklists into a "System" to identify issues.  If I then want to separate our QA servers from the PROD servers, I will have to create new "systems" and then upload the checklists into that new system.  

It would appear like a different view, such as a pivot table in Excel to isolate a particular aspect of data and then view issues for that platform.

**Comment by Cingulara** [comment]
What if we could allow a filter to the checklists to only show windows 10 or only show Oracle or only Java and all checklist listings and pie chart data shows?

**Comment by mtnnomad** [comment]
Yes, That would work.

**Comment by Cingulara** [comment]
We could have this under Reports possibly as well. 
* Choose the 'system checklist' report
* choose a system
* see the checklists
* allow filters on type of checklist

Until then, you can type into the "search" box where the checklists are all listed on the System page and filter it. In this example I typed 'outlook' to get the outlook checkbox.  You could try typing '2008' or 'WIN 10' or something similar that comes up in the title to limit the listing possibly @mtnnomad . 

![image](https://user-images.githubusercontent.com/46137145/71681179-fd1b8580-2d59-11ea-9d31-bdf7cff88e83.png)

**Comment by mtnnomad** [comment]
That works pretty well.

**Comment by DaleBinghamSoteriaSoft** [comment]
Feature set of v1.9.x of OpenRMF OSS will stay the way it is for a bit. So using the searchbox is the best way. 

In OpenRMF Professional, you can have 1,000's of checklists, Team Subpackages to segment an ATO or boundary to smaller teams, etc. to handle this.  This is only in professional https://www.soteriasoft.com/
