### ISSUE TITLE
[BUG]  Delete button to delete Nessus File upload information doesn't work

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openrmf-web#136]
**Describe the bug**
Delete button to delete Nessus File upload information doesn't work

**To Reproduce**
1. Go to System
2. Click on Your system
3. Click Edit 
4. Click delete button next to Nessus File

**Expected behavior**
Should delete the nessus file and uploaded data.

**Screenshots**
![image](https://user-images.githubusercontent.com/41908967/71606204-efd57f80-2b3c-11ea-9684-f334c1973294.png)

**Comment by Cingulara** [comment]
Fixed in 0.10.8
