### ISSUE TITLE
[BUG] Creating new system with no name makes NULL

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openrmf-web#137]
**Describe the bug**
If you upload a checklist and don't type in a system name it creates a system named NULL.

**Expected behavior**
Maybe verify if NULL is the response and show an error?

**Screenshots**
![image](https://user-images.githubusercontent.com/41908967/71606266-64102300-2b3d-11ea-93ce-5a97bf584470.png)

**Comment by Cingulara** [comment]
Fixed in 0.10.8
