### ISSUE TITLE
[FEATURE] Add a filter for severity (high, medium, low) on checklist for vulnerabilities shown

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-web#139]
**Is your feature request related to a problem? Please describe.**
Add in a filter for severity within each checklist, please.

**Describe the solution you'd like**
If I open up a system, select a checklist, and then look at the Vuln IDs, I want to be able to filter by High, Medium, Low in addition to Open, NaF, N/A and NR.  For instance, if I ask, "Show me all the OPEN and N/R findings for this checklist", I can deselect N/A and NaF and get that filtered result.   

![SortbySeverityHere](https://user-images.githubusercontent.com/57148328/71684298-52ec2f80-2d52-11ea-89af-4060f6aa3ece.PNG)

**Describe alternatives you've considered**
I cannot find other ways to do this.

Some other items that might work is to see the checklist metrics and click on the "Cat I" findings and have it create that filter for me with the check-boxes.  

![ClickbySeverityHere](https://user-images.githubusercontent.com/57148328/71684438-bbd3a780-2d52-11ea-835e-fc62084c11e9.PNG)

**Comment by Cingulara** [comment]
This is similar but not the same as #128

**Comment by mtnnomad** [comment]
Yes, similar.  I still cannot seem to sort by CAT level to see that level of V-IDs.  There is a view to show me how many, but not a link to open them up.  You're teasing me.  LOL

**Comment by Cingulara** [comment]
there is a filter on this now.
