### ISSUE TITLE
Loading large number of checklists for a system.  [BUG] 

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-web#140]
**Describe the bug**
Loaded 60 checklists into a System for 60 servers specific to a IE STIG and then attempted to do a compliance check for the system at the High level.  The window grayed out and spun for 10 minutes.  In the past I have left this to finish, and sometimes it does, other times it does not.  Sometimes it requires a complete reload/reconfigure of the app.

**To Reproduce**
1. Upload a large set of checklists into a system
2.  Go to compliance checker.
3.  Select the most returns (high) and generate.
4.  Generation will sometimes freeze the app.  I start the OpenRMF in a window and watch the processes dialog and when it did this there was an ASPCore.server.kestrel heartbeat takes longer than... notice that kept scrolling.  

**Expected behavior**
Compliance report generated without issues.

**Screenshots**
I will capture when I see it again and will update.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 79.0.3945.88

**Comment by Cingulara** [comment]
The datatables has a way to pull data from the API faster versus creating each row independently before displaying. This has to be done here for larger lists. We did it in the Professional version and it worked great.

**Comment by Cingulara** [comment]
The way compliance works is pulling message data and combining with the database to pull data and process it. I will have to investigate how this works to generate this across a large load. It may be the computer you are running on needs more CPU/memory for the docker engine to run. @mtnnomad can you say what your h/w and s/w platform was, the CPU and memory and swap for the docker engine, etc. so we can repeat?

**Comment by Cingulara** [comment]
I have a plan to combine some of the score/compliance/read/save/upload into a single API to reduce network latency and issues but that will have to wait until 2022 when I have time to rearchitect a good chunk of this. That may help as all the data will be in one database and codebase versus sending back/forth over the network.

**Comment by Cingulara** [comment]
Going to work on this with the v1.8 update.

In OpenRMF Professional we generate compliance, save it, then it takes MUCH less time to load. And we use it for the SSP and SAR info quickly as well. We are not going to do all that and history and stuff we do in Professional but have learned a few things revamping the compliance engine we can use as a model here as we get 1.8 out there.

**Comment by DaleBinghamSoteriaSoft** [comment]
What we have in v1.9 is how it will work to get data back.

OpenRMF Professional handles 1,000's or 10's of 1,000's of checklists and does all the compliance on the backend. This is only in professional https://www.soteriasoft.com/
