### ISSUE TITLE
Search filter shows more than requested.  

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-web#141]
**Describe the bug**
When loading multiple types of checklists into a system and then performing a search filter for specific checklists, other checklists remain in view.  If OS checklists and IE checklists are loaded into a system and a compliance check is performed, all checklists are displaced for the associated controls.  However, if I filter by "2012" or "MSIE" it will return results for only controls that are referenced in the checklist, unless a control is addressed by more than one checklist.  

I would expect if I filter for MSIE, only the MSIE checklists will be displayed.  

**To Reproduce**
1. Load more than one type of checklist into a system.
2. create a compliance check.
3. in the search field, isolate by checklist, i.e. "MSIE"
4. Notice in the display that AU-12 control is addressed in both MSIE STIGs and Server 2012 Stigs and thus are displayed, even though I only wanted to see MSIE.

**Expected behavior**
Include only checklists that match the query.  

**Screenshots**
See attached

![FIlterBug](https://user-images.githubusercontent.com/57148328/71748904-3115aa00-2e31-11ea-8ed4-2323fb9f9172.PNG)

**Comment by Cingulara** [comment]
That is because of how the data is rendered. The search filter up top filters "rows" and we put all links to checklists for a given control into a single row. So it works as we wrote it. We need to put each checklist into its own row in essence and that will fix this.

**Comment by Cingulara** [comment]
This is done now.
