### ISSUE TITLE
[FEATURE] Ability to convert checklists to new version

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openrmf-web#155]
**Is your feature request related to a problem? Please describe.**
We need a way to convert a current checklist to new checklist version/release within a system.

**Describe the solution you'd like**
![New-Checklist-Process](https://user-images.githubusercontent.com/41908967/73202218-92ffc180-4108-11ea-9e45-0aad7f089808.jpg)

The first half of this image. The second half is already done. 

**Additional context**
Something like this:
* Pull up the new checklist from the *manual-xccdf.xml file
* Pull up the old checklist
* For all the Asset info for the old one, copy into the new one
* For each VULN in the old one that has a corresponding VULN ID in the new one, copy all fields into the same fields into the new one (new one may have additional fields)
* For any new VULN ID, leave as Not Reviewed
* Save the new checklist as the latest, as long as there are no errors
* Update the version and release information metadata

**Comment by Cingulara** [comment]
This Asset section would basically just copy section for section if the OLD is in the NEW.

`<ASSET>
		<ROLE>None</ROLE>
		<ASSET_TYPE>Computing</ASSET_TYPE>
		<HOST_NAME>web1.myorg.mil</HOST_NAME>
		<HOST_IP></HOST_IP>
		<HOST_MAC></HOST_MAC>
		<HOST_FQDN></HOST_FQDN>
		<TECH_AREA></TECH_AREA>
		<TARGET_KEY>3009</TARGET_KEY>
		<WEB_OR_DATABASE>false</WEB_OR_DATABASE>
		<WEB_DB_SITE></WEB_DB_SITE>
		<WEB_DB_INSTANCE></WEB_DB_INSTANCE>
	</ASSET>`

**Comment by Cingulara** [comment]
This section below that has initial metadata on the STIG should have similar things, but would copy if in OLD then in NEW in the same field. 

`
		<iSTIG>
			<STIG_INFO>
				<SI_DATA>
					<SID_NAME>version</SID_NAME>
					<SID_DATA>4</SID_DATA>
				</SI_DATA>`

**Comment by Cingulara** [comment]
The vulnerability area we would cycle through the older ones, and if the VULN ID in the old one is in the new one, then copy the STIG DATA multiple fields

`<VULN>
				<STIG_DATA>
					<VULN_ATTRIBUTE>Vuln_Num</VULN_ATTRIBUTE>
					<ATTRIBUTE_DATA>V-69239</ATTRIBUTE_DATA>
				</STIG_DATA>`

You would also copy the ending fields before the /VULN as well:

`<STATUS>Open</STATUS>
				<FINDING_DETAILS></FINDING_DETAILS>
				<COMMENTS></COMMENTS>
				<SEVERITY_OVERRIDE></SEVERITY_OVERRIDE>
				<SEVERITY_JUSTIFICATION></SEVERITY_JUSTIFICATION>`
