### ISSUE TITLE
Saving an edited checklist

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openrmf-web#163]
**Describe the bug**
When I edit a checklist on the system information page it does not save when I change the role
![image](https://user-images.githubusercontent.com/41908967/75071006-70bc5200-54c2-11ea-9cb1-4f3aa668de64.png)

**To Reproduce**
1. Go to The Systems page
2. Click on the name of the system
3. Click on checklist
4. Click Edit

**Expected behavior**
It should save th change to the role
**Screenshots**
![image](https://user-images.githubusercontent.com/41908967/75071103-a82afe80-54c2-11ea-8dfa-eab6c521ebc4.png)

**Comment by Cingulara** [comment]
When you save, then close it updates the Role on the screen. however, when you go back to edit it is not set right. The select box is not being set possibly when you load or reload the page. That has to be looked at.

**Comment by Cingulara** [comment]
This line was missing
`$("#frmChecklistRole").val(data.checklist.asset.role);`
