### ISSUE TITLE
[FEATURE] Incorporate CNSSI 1253 amplifications

### ISSUE THREAD

**Issue by IvanDrag0** [Cingulara/openrmf-web#166]
**Is your feature request related to a problem? Please describe.**
While NIST 800-53 is the basis for the RMF process and controls, for a lot of other applications (especially within the DoD), we also require the CNSSI 1253 amplifications for the controls. Without those amplifications, the control baseline for those system would not be complete.

**Describe the solution you'd like**
The software should integrate the CNSSI 1253 controls and change the system categorization from Low, Moderate, High, to allow each of the C-I-A categories to have an independent categorization (H-H-H, instead of just High, etc.) .

**Describe alternatives you've considered**
There are no current alternatives except getting the manual categorization and use a spreadsheet.

**Additional context**
I can provide a spreadsheet with the CNSSI control breakdown if that would help.

**Comment by Cingulara** [comment]
@IvanDrag0 yes a spreadsheet w/ the data for clarification would be great thank you. Either here or in https://join.slack.com/t/openrmftool/shared_invite/zt-ck8lqld0-8LD7k66mzj7WsIno9YFrMg the Slack channel we setup. I leave that choice up to you, whatever is easier. 

Thanks. It would be good to see it visually and compare to what we have going on so far.

**Comment by Cingulara** [comment]
This is now in the Professional v2.3 version at https://www.soteriasoft.com/. CNNSI overlays and the ability to add other overlays and apply them. You can add at the "application wide" level and pull into your system package. Or you can just create at the system package level. And it lets you save as JSON and load a JSON file to share them with other installations.

This is going into the Professional version, not OSS.
