### ISSUE TITLE
Setup an online version of this that can be hit

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openrmf-web#52]
We need a way to showcase the tool online to people to allow them to touch/feel/use/test

* web based 100%
* Need security and JWT tokens / fronted by Kong for authN/authZ
* Needs to warn on uploading REAL checklists (we will have some loaded by default)
* Needs to reset data to default nightly

Can be in Fargate, Digital Ocean, OpenShift online, etc.

**Comment by Cingulara** [comment]
Got the k8s helm chart working finally!

**Comment by Cingulara** [comment]
Adding here https://github.com/Cingulara/openrmf-io
