### ISSUE TITLE
When exporting a checklist, only export the VULNS you are showing

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openrmf-web#57]
* if you filter by status type, only show those visible in XLS

* if you are filtering by the control only show those in the XLS

**Comment by Cingulara** [comment]
On the single checklist page, if you have a filter, download all Vuln IDs and the corresponding detailed information into XLS like we do the regular export to Excel. It just shows only the Vuln Ids currently viewed.

**Comment by Cingulara** [comment]
Basically I export and list the VULNS and do a "foreach".

I need to pass in the checkboxes for the 4 filters, and if "on" then show the VULN IDs for the regular listing that is NOT the "by control number" listing off compliance.

**Comment by Cingulara** [comment]
For compliance, I need to pull in the Vuln ID's and then say "for each of the listed, if in the Control Set of VULN IDs then show and download in XLSX.

**Comment by Cingulara** [comment]
Got the 'view the checklist and change filters' export to match that now in EXCEL ;) so I need to do the compliance listing next from the compliance generator.
