### ISSUE TITLE
allow editing of the checklist online

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-web#62]

**Comment by Cingulara** [comment]
Add in the Security Override dropdown and guidance / text as well as the Status, Comments, and Finding.

**Comment by degthat8412** [comment]
Client side validation should be required for N/A, closed or severity over a comment should be required as this needs to be explained how you support that status with justification.

**Comment by Cingulara** [comment]
We are going to have a few areas you can save. One is at the top Asset area where you can set these options and save the data back to the Save API to a new PUT /artifact/{id}/assetinfo type of API that saves the data after some validation.

The Edit button would allow editing of more information...OR...you edit in line and then click Save. I like the Edit button popup better so it forces a save of all data at once. 
![image](https://user-images.githubusercontent.com/46137145/74787344-f5b62a00-527c-11ea-9dd4-22b7393a9d5b.png)

This is the checklist area in the CKL file that would get updated.
![image](https://user-images.githubusercontent.com/46137145/74787096-47aa8000-527c-11ea-9a3c-dad55985818e.png)

**Comment by Cingulara** [comment]
If you have editing rights, along with the above data you can edit the individual Vulnerability information one at a time. As you edit one, you click Save, it will save back that specific piece into the system. 

For this, we can have a PUT on the /artifact/{id}/vulnerability/{vulnid}/ that puts the data for updating this specific piece. It would validate the data and update the current VULN_ID record for the following fields:
* Status (dropdown listing box) -- 1 of the 4
* Comments (textbox)
* Details (textbox)
* Severity Override (need to add to the page)
* Severity Override Justification (need to add to the page)

Just like the other screens, you can edit to a popup floating box on there letting you specify these 5 things and then save. If a successful save, the VULN ID updates and displays correctly as the "OK" button makes the edit dialog go away.

![image](https://user-images.githubusercontent.com/46137145/74787467-43329700-527d-11ea-82e2-61713049625a.png)

**Comment by Cingulara** [comment]
Any save of a vulnerability should trigger a few things:
* audit of the save/update
* a publish of "openrmf.checklist.save.update"" with the artifactId to pickup

Any save of the asset information should trigger a few things:
* audit of the save/update

**Comment by Cingulara** [comment]
Editing the top ASSET type info is done right and seems to work. We will test more to be sure. This is for 1 edit at a time. 

I have 1/2 of the VULN editing setup. I need to do the popup floating window, set and save the data, and call the API back. 

I also need to do input validation on special characters to/from to make sure I do not introduce HTML characters to mess the page up. I have maxlength, but need input validation. I also need to set limits on the comments and finding details textareas so people do not go overboard.
